spring.application.name=you-say-app
my.db.url=jdbc:mysql://localhost:3306/you_say?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B9&rewriteBatchedStatements=true
my.db.user=root
my.db.pass=Shigeto1219

#URLにセッションつかないように
server.servlet.session.tracking-modes=cookie